---
- name: Restart postgresql
  ansible.builtin.systemd:
    name: "{{ postgresql_service_name }}"
    state: restarted

- name: Reload postgresql
  ansible.builtin.systemd:
    name: "{{ postgresql_service_name }}"
    state: reloaded
