#!/usr/bin/env python3
"""Mirror container images into apps/registry via skopeo, digest preserved.

Two subcommands, deliberately separate:

    resolve   Look up the current raw-manifest digest for every tag in
              tools/image_pins.yml and write it to tools/image_pins.lock.yml.
              Never touches the registry. Safe to run any time; re-run
              after editing image_pins.yml.

    sync      Copy each digest locked in tools/image_pins.lock.yml into
              the registry (docker://<hostname>/<dest_repo>:<tag>) and
              verify the pushed manifest's own digest matches before
              considering it done. Refuses to run if a tag has moved
              since the last resolve, or if any image has no lock entry
              at all.

This split mirrors the repo's existing pin-bump discipline (see
requirements.yml and docs/CHANGE_CONTROL.md): resolving a new digest is a
visible, reviewable file change, not something that happens silently in
the same step that pushes bytes to the registry.

The digest used throughout is the sha256 of the raw manifest bytes as
returned by `skopeo inspect --raw`, computed locally rather than trusted
from `skopeo inspect`'s parsed `.Digest` field — for a multi-arch source
(a manifest list/OCI index), `.Digest` can resolve to a single platform's
manifest rather than the list itself depending on skopeo version and
negotiated Accept headers. Hashing the raw bytes ourselves is unambiguous
and matches how registries compute content digests per the OCI spec, and
`skopeo copy --multi-arch all` against that exact digest reference then
copies the whole list (or the single manifest, if that's what it is).

Credentials come from environment variables, never from image_pins.yml:
    SKOPEO_SRC_USERNAME / SKOPEO_SRC_PASSWORD   optional, private sources
    SKOPEO_DEST_USERNAME / SKOPEO_DEST_PASSWORD required for `sync`
        (apps/registry mandates auth — see apps/registry/tasks/secrets.yml)

Usage:
    python tools/sync_images_with_skopeo.py resolve
    python tools/sync_images_with_skopeo.py resolve --only netbox --force
    python tools/sync_images_with_skopeo.py sync --dry-run
    python tools/sync_images_with_skopeo.py sync --only k8s_pause

Requires: PyYAML (pip install -r tools/requirements.txt) and the `skopeo`
binary on PATH on whichever control node runs this — not a target-host
dependency, same category as pyvmomi/pywinrm/proxmoxer in requirements.yml.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PINS = REPO_ROOT / "tools" / "image_pins.yml"
DEFAULT_LOCK = REPO_ROOT / "tools" / "image_pins.lock.yml"

DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")

LOCK_HEADER = """\
---
# GENERATED by tools/sync_images_with_skopeo.py resolve — do not
# hand-edit. See tools/image_pins.yml for the human-maintained
# source/tag list this locks against. A changed digest for an unchanged
# tag means upstream repointed that tag — treat it like a
# requirements.yml version bump (docs/CHANGE_CONTROL.md): review why it
# changed before merging.
"""


class ConfigError(Exception):
    pass


class SkopeoError(Exception):
    pass


def require_skopeo() -> None:
    if shutil.which("skopeo") is None:
        raise SystemExit(
            "skopeo is not on PATH. Install it on this control node "
            "(e.g. `dnf install skopeo` / `apt install skopeo`) before "
            "running this script."
        )


def load_pins(path: Path) -> dict:
    if not path.exists():
        raise ConfigError(f"{path} does not exist")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if "registry" not in data or "images" not in data:
        raise ConfigError(f"{path}: expected top-level 'registry' and 'images' keys")

    names = [img.get("name") for img in data["images"]]
    if len(names) != len(set(names)):
        dupes = sorted({n for n in names if names.count(n) > 1})
        raise ConfigError(f"{path}: duplicate image name(s) {dupes}")

    for img in data["images"]:
        missing = [k for k in ("name", "source", "tag", "dest_repo") if not img.get(k)]
        if missing:
            raise ConfigError(f"{path}: image entry {img} missing required key(s) {missing}")

    return data


def load_lock(path: Path) -> dict:
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data.get("locked", {}) or {}


def write_atomic(path: Path, content: str) -> None:
    fd, tmp_path = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        os.replace(tmp_path, path)
    except BaseException:
        Path(tmp_path).unlink(missing_ok=True)
        raise


def write_lock(path: Path, locked: dict) -> None:
    body = yaml.safe_dump({"locked": locked}, sort_keys=True, default_flow_style=False)
    write_atomic(path, LOCK_HEADER + body)


def run_skopeo(args: list[str]) -> subprocess.CompletedProcess:
    proc = subprocess.run(["skopeo", *args], capture_output=True)
    if proc.returncode != 0:
        raise SkopeoError(
            f"skopeo {' '.join(args)} failed (exit {proc.returncode}): "
            f"{proc.stderr.decode(errors='replace').strip()}"
        )
    return proc


def src_creds_args() -> list[str]:
    user, pw = os.environ.get("SKOPEO_SRC_USERNAME"), os.environ.get("SKOPEO_SRC_PASSWORD")
    return ["--creds", f"{user}:{pw}"] if user and pw else []


def dest_creds_args() -> list[str]:
    user, pw = os.environ.get("SKOPEO_DEST_USERNAME"), os.environ.get("SKOPEO_DEST_PASSWORD")
    if not (user and pw):
        raise SystemExit(
            "SKOPEO_DEST_USERNAME and SKOPEO_DEST_PASSWORD must both be set "
            "in the environment to sync into the registry (never pass "
            "credentials on the command line or store them in "
            "tools/image_pins.yml)."
        )
    return ["--creds", f"{user}:{pw}"]


def tls_args(prefix: str, registry_cfg: dict) -> list[str]:
    args = []
    if registry_cfg.get("cert_dir"):
        args += [f"--{prefix}-cert-dir", registry_cfg["cert_dir"]]
    if registry_cfg.get("insecure"):
        args += [f"--{prefix}-tls-verify", "false"]
    return args


def raw_manifest_digest(ref: str, creds_args: list[str], extra_tls_args: list[str]) -> str:
    proc = run_skopeo(["inspect", "--raw", *creds_args, *extra_tls_args, f"docker://{ref}"])
    return "sha256:" + hashlib.sha256(proc.stdout).hexdigest()


def select_images(images: list[dict], only: list[str] | None) -> list[dict]:
    if not only:
        return images
    by_name = {img["name"]: img for img in images}
    unknown = set(only) - set(by_name)
    if unknown:
        raise ConfigError(f"--only name(s) not found in image_pins.yml: {sorted(unknown)}")
    return [by_name[name] for name in only]


def cmd_resolve(args: argparse.Namespace) -> int:
    pins = load_pins(Path(args.pins))
    lock_path = Path(args.lock)
    locked = load_lock(lock_path)
    images = select_images(pins["images"], args.only)

    errors: list[str] = []
    for img in images:
        name, source, tag = img["name"], img["source"], img["tag"]
        existing = locked.get(name)
        if existing and existing.get("tag") == tag and not args.force:
            print(f"skip {name}: already locked to tag {tag} ({existing.get('digest')})")
            continue
        ref = f"{source}:{tag}"
        try:
            digest = raw_manifest_digest(ref, src_creds_args(), [])
        except SkopeoError as exc:
            errors.append(f"{name} ({ref}): {exc}")
            continue
        locked[name] = {
            "tag": tag,
            "digest": digest,
            "resolved_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }
        print(f"resolved {name}: {ref} -> {digest}")

    # Drop lock entries for images no longer declared in image_pins.yml,
    # so the lock file never carries stale/orphaned pins.
    known_names = {img["name"] for img in pins["images"]}
    for stale in set(locked) - known_names:
        print(f"removing stale lock entry for '{stale}' (no longer in image_pins.yml)")
        del locked[stale]

    write_lock(lock_path, locked)
    print(f"wrote {lock_path}")

    if errors:
        print(f"\n{len(errors)} image(s) failed to resolve:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    return 0


def cmd_sync(args: argparse.Namespace) -> int:
    pins = load_pins(Path(args.pins))
    registry_cfg = pins["registry"]
    hostname = registry_cfg.get("hostname", "")
    if not hostname or hostname == "CHANGEME":
        raise SystemExit(
            "tools/image_pins.yml: registry.hostname is still CHANGEME — "
            "set it before running sync, dry-run included."
        )

    locked = load_lock(Path(args.lock))
    images = select_images(pins["images"], args.only)

    plan_errors: list[str] = []
    plan: list[tuple[dict, str]] = []
    for img in images:
        name, tag = img["name"], img["tag"]
        entry = locked.get(name)
        if entry is None:
            plan_errors.append(f"{name}: no lock entry — run `resolve` first")
            continue
        if entry.get("tag") != tag:
            plan_errors.append(
                f"{name}: image_pins.yml has tag '{tag}' but the lock file "
                f"has tag '{entry.get('tag')}' — the tag moved since the "
                f"last resolve, run `resolve` again and review the diff "
                f"before syncing"
            )
            continue
        digest = entry.get("digest", "")
        if not DIGEST_RE.match(digest or ""):
            plan_errors.append(f"{name}: lock digest '{digest}' is not a valid sha256 digest")
            continue
        plan.append((img, digest))

    if plan_errors:
        print("Refusing to sync:", file=sys.stderr)
        for e in plan_errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    dest_tls = tls_args("dest", registry_cfg)
    failures: list[str] = []

    for img, digest in plan:
        src_ref = f"{img['source']}@{digest}"
        dest_ref = f"{hostname}/{img['dest_repo']}:{img['tag']}"

        if args.dry_run:
            try:
                current = raw_manifest_digest(dest_ref, dest_creds_args_dry(), dest_tls)
                status = "in sync" if current == digest else f"WOULD OVERWRITE (dest currently {current})"
            except SkopeoError:
                status = "would push (not present in registry yet)"
            print(f"{img['name']}: {src_ref} -> {dest_ref}  [{status}]")
            continue

        try:
            run_skopeo([
                "copy", "--multi-arch", "all",
                *src_creds_args(),
                *dest_creds_args(), *dest_tls,
                f"docker://{src_ref}", f"docker://{dest_ref}",
            ])
            pushed = raw_manifest_digest(dest_ref, dest_creds_args(), dest_tls)
            if pushed != digest:
                failures.append(
                    f"{img['name']}: pushed but resulting digest {pushed} != "
                    f"locked digest {digest} — registry may have mutated the "
                    f"manifest; treat this as a hard failure and investigate"
                )
                continue
            print(f"synced {img['name']}: {dest_ref} @ {digest}")
        except SkopeoError as exc:
            failures.append(f"{img['name']}: {exc}")

    if failures:
        print(f"\n{len(failures)} image(s) failed to sync:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    return 0


def dest_creds_args_dry() -> list[str]:
    # Dry-run should work without SKOPEO_DEST_* set (e.g. a first-ever
    # run against an empty registry, or a read-only credential check) —
    # only require dest creds when actually about to push.
    user, pw = os.environ.get("SKOPEO_DEST_USERNAME"), os.environ.get("SKOPEO_DEST_PASSWORD")
    return ["--creds", f"{user}:{pw}"] if user and pw else []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--pins", default=str(DEFAULT_PINS))
    parser.add_argument("--lock", default=str(DEFAULT_LOCK))
    sub = parser.add_subparsers(dest="command", required=True)

    p_resolve = sub.add_parser("resolve", help="look up digests for tags, write the lock file")
    p_resolve.add_argument("--only", action="append", help="limit to this image name (repeatable)")
    p_resolve.add_argument("--force", action="store_true", help="re-resolve even if the tag already has a matching lock entry")
    p_resolve.set_defaults(func=cmd_resolve)

    p_sync = sub.add_parser("sync", help="copy locked digests into the registry")
    p_sync.add_argument("--only", action="append", help="limit to this image name (repeatable)")
    p_sync.add_argument("--dry-run", action="store_true", help="report what would change, push nothing")
    p_sync.set_defaults(func=cmd_sync)

    args = parser.parse_args()
    require_skopeo()
    try:
        return args.func(args)
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
